apiVersion: v1
kind: Service
metadata:
  labels:
    app: aggregator-service
  name: aggregator-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: aggregator-api
  type: LoadBalancer
